sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    packages:
    - libssl-dev
    - libgtk2.0-dev
    - libglib2.0-dev
    - libldns-dev
    - clang
script:
  - ./configure --enable-debug --with-forward-zones-support
  - make
  - make test
